import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { pillars } from "../../data/servicesContent";
import AnimatedButton from "../ui/animated-button";
import SectionContainer from "../ui/section-container";
import { motion, useReducedMotion } from "framer-motion";
const PillarMap = () => {
    const reduceMotion = useReducedMotion();
    return (_jsxs(SectionContainer, { className: "space-y-6 py-10", children: [_jsxs("div", { className: "space-y-2 text-slate-900 dark:text-white", children: [_jsx("p", { className: "text-xs uppercase tracking-[0.2em] text-solara-navy dark:text-indigo-200", children: "Pillars" }), _jsx("h2", { className: "text-3xl font-semibold", children: "Plan, coordinate, and sustain" }), _jsx("p", { className: "text-sm text-slate-700 dark:text-slate-200/80", children: "Each pillar links to the next so you never lose momentum." })] }), _jsx("div", { className: "grid gap-4 lg:grid-cols-3", children: pillars.map((pillar, idx) => (_jsxs(motion.div, { initial: { opacity: 0, y: reduceMotion ? 0 : 14 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.25 }, transition: { duration: reduceMotion ? 0.1 : 0.45, delay: idx * 0.05 }, className: "flex flex-col gap-3 rounded-2xl border border-white/50 bg-white/80 p-5 text-slate-900 shadow-[0_22px_80px_rgba(0,51,102,0.26)] backdrop-blur-2xl dark:border-white/10 dark:bg-white/5 dark:text-white", children: [_jsxs("div", { className: "flex items-center gap-2 text-sm font-semibold uppercase tracking-[0.14em] text-solara-navy dark:text-indigo-200", children: [_jsx("span", { className: "h-2 w-2 rounded-full bg-[#ffd700]", "aria-hidden": true }), pillar.title] }), _jsx("p", { className: "text-sm text-slate-700 dark:text-slate-200/85", children: pillar.description }), _jsx("ul", { className: "space-y-2 text-sm text-slate-800 dark:text-slate-100", children: pillar.bullets.map((bullet) => (_jsxs("li", { className: "flex items-start gap-2", children: [_jsx("span", { className: "mt-1 h-1.5 w-1.5 rounded-full bg-[#007bff]", "aria-hidden": true }), _jsx("span", { children: bullet })] }, bullet))) }), _jsx(AnimatedButton, { href: pillar.cta.href, className: "mt-auto w-full justify-center px-4 py-2", children: pillar.cta.label })] }, pillar.id))) })] }));
};
export default PillarMap;
