package com.solara.backend.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.time.Instant;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * Stores per-user notification settings for the in-app inbox.
 */
@Entity
@Table(
        name = "notification_preferences",
        indexes = {
                @Index(name = "idx_notification_preferences_user", columnList = "user_id")
        },
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_notification_preferences_user", columnNames = "user_id")
        }
)
public class NotificationPreference {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Top-level switch for in-app notifications.
     */
    @Column(name = "in_app_enabled", nullable = false)
    private boolean inAppEnabled = true;

    /**
     * Controls help-request notifications.
     */
    @Column(name = "help_requests_enabled", nullable = false)
    private boolean helpRequestsEnabled = true;

    /**
     * Controls notifications generated by project resource updates.
     */
    @Column(name = "project_resources_enabled", nullable = false)
    private boolean projectResourcesEnabled = true;

    @Column(name = "team_activity_enabled", nullable = false)
    private boolean teamActivityEnabled = true;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public boolean isInAppEnabled() {
        return inAppEnabled;
    }

    public void setInAppEnabled(boolean inAppEnabled) {
        this.inAppEnabled = inAppEnabled;
    }

    public boolean isHelpRequestsEnabled() {
        return helpRequestsEnabled;
    }

    public void setHelpRequestsEnabled(boolean helpRequestsEnabled) {
        this.helpRequestsEnabled = helpRequestsEnabled;
    }

    public boolean isProjectResourcesEnabled() {
        return projectResourcesEnabled;
    }

    public void setProjectResourcesEnabled(boolean projectResourcesEnabled) {
        this.projectResourcesEnabled = projectResourcesEnabled;
    }

    public boolean isTeamActivityEnabled() {
        return teamActivityEnabled;
    }

    public void setTeamActivityEnabled(boolean teamActivityEnabled) {
        this.teamActivityEnabled = teamActivityEnabled;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
