import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import AnimatedButton from "../ui/animated-button";
import { ShieldCheck } from "lucide-react";
const levelCopy = {
    community: "Guidance, photos, checklists, and remote support.",
    trained: "Peer review, site walkthroughs, and tool coaching.",
    certified: "Mains wiring, commissioning, and formal sign-off.",
};
const HelperProfileDrawer = ({ helper, open, onOpenChange, onRequest }) => {
    if (!helper || !open)
        return null;
    return (_jsxs("div", { className: "fixed inset-0 z-50 flex items-center justify-center", children: [_jsx("div", { className: "absolute inset-0 bg-black/50 backdrop-blur-sm", onClick: () => onOpenChange(false), "aria-hidden": true }), _jsxs("div", { className: "relative z-10 w-[95vw] max-w-2xl rounded-2xl border border-white/10 bg-white/90 p-5 text-slate-900 shadow-2xl backdrop-blur-2xl dark:bg-[#0a0f1e] dark:text-white", children: [_jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("p", { className: "text-xl font-semibold", children: helper.name }), helper.verified && _jsx(ShieldCheck, { className: "h-4 w-4 text-solara-gold" })] }), _jsx("p", { className: "text-sm text-slate-700 dark:text-slate-200", children: levelCopy[helper.level] })] }), _jsx("button", { type: "button", onClick: () => onOpenChange(false), className: "rounded-full border border-white/50 bg-white/60 px-2 py-1 text-xs font-semibold text-slate-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-solara-blue dark:border-white/10 dark:bg-white/10 dark:text-white", children: "Close" })] }), _jsxs("div", { className: "mt-3 space-y-2 text-sm text-slate-700 dark:text-slate-200", children: [_jsx("p", { children: helper.bio }), _jsxs("p", { className: "text-xs text-slate-600 dark:text-slate-300", children: ["Support types: ", helper.supportTypes.join(", "), " \u00B7 Response: ", helper.responseTimeLabel] }), _jsx("div", { className: "flex flex-wrap gap-2", children: helper.skills.map((skill) => (_jsx("span", { className: "rounded-full border border-white/50 bg-white/70 px-2 py-1 text-xs font-semibold text-slate-800 dark:border-white/10 dark:bg-white/10 dark:text-slate-100", children: skill }, skill))) }), _jsx("p", { className: "text-xs text-slate-600 dark:text-slate-300", children: "Any work involving mains wiring requires a certified professional." })] }), _jsxs("div", { className: "mt-4 flex flex-wrap gap-2", children: [_jsx(AnimatedButton, { onClick: () => onRequest(helper), className: "px-4 py-2", children: "Request support" }), _jsx(AnimatedButton, { variant: "outline", className: "px-4 py-2", children: "Save helper" })] })] })] }));
};
export default HelperProfileDrawer;
