import type { EnergyEstimate } from "../hooks/useEnergyEstimate";
import type { Panel, Obstacle, BatteryConfig, RoofConfig } from "../hooks/useConfiguratorStore";

interface PdfExportData {
  roof: RoofConfig;
  panels: Panel[];
  obstacles: Obstacle[];
  battery: BatteryConfig;
  estimate: EnergyEstimate;
}

export async function generateConfiguratorPdf(data: PdfExportData): Promise<void> {
  const { jsPDF } = await import("jspdf");

  const { roof, panels, obstacles, battery, estimate } = data;
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = margin;

  const addSectionHeader = (title: string) => {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 58, 95);
    doc.text(title, margin, yPos);
    yPos += 8;
  };

  const addRow = (label: string, value: string) => {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    doc.text(label, margin, yPos);
    doc.text(value, pageWidth - margin - doc.getTextWidth(value), yPos);
    yPos += 6;
  };

  const addDivider = () => {
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 8;
  };

  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 58, 95);
  doc.text("Solar System Configuration", margin, yPos);
  yPos += 10;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("Generated by Solara 3D Configurator", margin, yPos);
  yPos += 6;
  doc.text(new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }), margin, yPos);
  yPos += 15;

  addDivider();

  addSectionHeader("System Overview");
  addRow("Solar Panels", `${estimate.panelCount} panels`);
  addRow("System Size", `${estimate.systemSizeKw} kW`);
  if (battery.count > 0) {
    addRow("Battery Storage", `${battery.count} unit${battery.count > 1 ? "s" : ""} (${estimate.batteryCapacityKwh} kWh)`);
  }
  if (obstacles.length > 0) {
    addRow("Roof Obstacles", `${obstacles.length} obstacle${obstacles.length > 1 ? "s" : ""}`);
  }
  yPos += 5;

  addDivider();

  addSectionHeader("Roof Configuration");
  addRow("Roof Type", roof.type.charAt(0).toUpperCase() + roof.type.slice(1));
  addRow("Dimensions", `${roof.width}m x ${roof.depth}m`);
  addRow("Pitch Angle", `${roof.pitchAngle} deg`);
  addRow("Orientation", `${roof.orientation} deg from south`);
  yPos += 5;

  addDivider();

  addSectionHeader("Estimated Annual Performance");
  addRow("Annual Generation", `${estimate.annualKwh.toLocaleString()} kWh`);
  addRow("Self-Consumed", `${estimate.selfConsumedKwh.toLocaleString()} kWh (${estimate.selfConsumptionRate}%)`);
  addRow("Exported to Grid", `${estimate.exportedKwh.toLocaleString()} kWh`);
  yPos += 5;

  addDivider();

  addSectionHeader("Financial Summary");
  addRow("Annual Savings", `GBP ${estimate.annualSavingsGbp.toLocaleString()}`);
  addRow("25-Year Savings", `GBP ${estimate.lifetimeSavingsGbp.toLocaleString()}`);
  addRow("Estimated Payback", `~${estimate.paybackYears} years`);
  yPos += 5;

  addDivider();

  addSectionHeader("Environmental Impact");
  addRow("Annual CO2 Savings", `${(estimate.annualCo2Kg / 1000).toFixed(2)} tonnes`);
  addRow("25-Year CO2 Savings", `${((estimate.annualCo2Kg * 25) / 1000).toFixed(1)} tonnes`);
  yPos += 10;

  if (yPos < 200) {
    addDivider();
    addSectionHeader("Roof Layout");
    yPos += 5;

    const diagramWidth = 100;
    const diagramHeight = (roof.depth / roof.width) * diagramWidth;
    const diagramX = (pageWidth - diagramWidth) / 2;
    const diagramY = yPos;

    doc.setDrawColor(100, 100, 100);
    doc.setFillColor(240, 240, 240);
    doc.rect(diagramX, diagramY, diagramWidth, diagramHeight, "FD");

    if (roof.type === "gabled") {
      doc.setDrawColor(80, 80, 80);
      doc.setLineWidth(0.5);
      doc.line(diagramX + diagramWidth / 2, diagramY, diagramX + diagramWidth / 2, diagramY + diagramHeight);
    }

    const scale = diagramWidth / roof.width;
    doc.setFillColor(30, 58, 95);
    panels.forEach((panel) => {
      const px = diagramX + diagramWidth / 2 + panel.position[0] * scale - 8;
      const py = diagramY + diagramHeight / 2 + panel.position[2] * scale - 5;
      doc.rect(px, py, 16, 10, "F");
    });

    doc.setFillColor(139, 69, 19);
    obstacles.forEach((obs) => {
      const ox = diagramX + diagramWidth / 2 + obs.position[0] * scale - 4;
      const oy = diagramY + diagramHeight / 2 + obs.position[2] * scale - 4;
      doc.rect(ox, oy, 8, 8, "F");
    });

    yPos = diagramY + diagramHeight + 15;
  }

  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(120, 120, 120);
  const disclaimerY = doc.internal.pageSize.getHeight() - 25;
  doc.text("Disclaimer: These estimates are based on typical UK conditions for the London region.", margin, disclaimerY);
  doc.text("Actual performance depends on shading, weather, and installation quality.", margin, disclaimerY + 4);
  doc.text("Please consult with a certified installer for accurate quotes.", margin, disclaimerY + 8);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("Generated by Solara - solara.community", pageWidth / 2, doc.internal.pageSize.getHeight() - 10, {
    align: "center",
  });

  doc.save(`solara-solar-config-${Date.now()}.pdf`);
}
