import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import ActionRail from "@/components/ui/action-rail";
import PageFrame from "@/components/ui/page-frame";
import PageHeroStage from "@/components/ui/page-hero-stage";
import PageReveal from "@/components/ui/page-reveal";
import PreviewFrame from "@/components/ui/preview-frame";
import SurfacePanel from "@/components/ui/surface-panel";
const CommunityGuidelines = () => (_jsxs(PageFrame, { family: "editorial", width: "wide", density: "compact", children: [_jsx(PageReveal, { mode: "mount", children: _jsx(PageHeroStage, { family: "guide", eyebrow: "Community guidelines", title: "A respectful, inclusive solar community.", body: "Solara is for neighbors helping neighbors. Keep interactions honest, inclusive, and free from scams or misrepresentation.", metrics: [
                    { label: "Baseline", value: "Respect first", meta: "Participation starts with safety, honesty, and inclusion." },
                    { label: "Moderation", value: "Report early", meta: "Flag scams, harassment, or unsafe advice quickly." },
                    { label: "Boundary", value: "No false claims", meta: "Qualifications and risk should stay transparent." },
                ], preview: _jsx(PreviewFrame, { chromeLabel: "Community expectations", eyebrow: "Shared standards", title: "The platform works when people are specific, respectful, and honest about scope.", body: "Good collaboration starts with clarity about skill, safety, and the role community members are actually playing.", children: _jsx(ActionRail, { compact: true, items: [
                            { eyebrow: "Respect", title: "Keep the space inclusive and non-discriminatory.", body: "Treat neighbors, volunteers, and certified professionals with the same baseline respect." },
                            { eyebrow: "Transparency", title: "State your real qualifications.", body: "Do not overstate experience, certification, or the risk of a task." },
                            { eyebrow: "Escalation", title: "Report bad behavior before it spreads.", body: "Unsafe advice and harassment should be paused quickly, not debated into normalcy." },
                        ] }) }) }) }), _jsx(PageReveal, { mode: "in-view", children: _jsxs("div", { className: "grid gap-4 lg:grid-cols-2", children: [_jsx(SurfacePanel, { as: "article", variant: "guide", layout: "preview", children: _jsxs("div", { className: "space-y-3", children: [_jsx("h2", { className: "text-lg font-semibold text-slate-900 dark:text-white", children: "Principles" }), _jsxs("ul", { className: "list-inside list-disc space-y-2 text-sm text-slate-700 dark:text-slate-200", children: [_jsx("li", { children: "Respect, inclusion, and non-discrimination." }), _jsx("li", { children: "Transparent skills and qualifications; no false claims." }), _jsx("li", { children: "Safety-first: pause if something feels risky." }), _jsx("li", { children: "Credit others' work and share knowledge openly." })] })] }) }), _jsx(SurfacePanel, { as: "article", variant: "guide", layout: "preview", children: _jsxs("div", { className: "space-y-3", children: [_jsx("h2", { className: "text-lg font-semibold text-slate-900 dark:text-white", children: "Reporting & moderation" }), _jsxs("ul", { className: "list-inside list-disc space-y-2 text-sm text-slate-700 dark:text-slate-200", children: [_jsx("li", { children: "Flag scams, harassment, or unsafe advice." }), _jsx("li", { children: "Organisers can remove posts or pause collaboration." }), _jsx("li", { children: "Repeat violations may be removed from Solara spaces." })] })] }) })] }) }), _jsx(PageReveal, { mode: "in-view", children: _jsx(SurfacePanel, { as: "article", variant: "guide", layout: "closeout", children: _jsxs("div", { className: "space-y-3", children: [_jsx("h2", { className: "text-lg font-semibold text-slate-900 dark:text-white", children: "Professional boundaries" }), _jsx("p", { className: "text-sm text-slate-700 dark:text-slate-200", children: "Helpers are community members, not employees of Solara. For high-risk electrical work, use certified professionals." })] }) }) })] }));
export default CommunityGuidelines;
