import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import ActionRail from "@/components/ui/action-rail";
import PageFrame from "@/components/ui/page-frame";
import PageHeroStage from "@/components/ui/page-hero-stage";
import PageReveal from "@/components/ui/page-reveal";
import PreviewFrame from "@/components/ui/preview-frame";
import SurfacePanel from "@/components/ui/surface-panel";
const Safety = () => (_jsxs(PageFrame, { family: "editorial", width: "wide", density: "compact", children: [_jsx(PageReveal, { mode: "mount", children: _jsx(PageHeroStage, { family: "guide", eyebrow: "Safety & scope", title: "Work safely, stay within scope.", body: "Solara is a community platform. Helpers are community members, not employees of Solara. Always follow local regulations and use licensed professionals for high-risk work.", metrics: [
                    { label: "High-risk work", value: "Certified only", meta: "Use licensed professionals where required." },
                    { label: "Community role", value: "Neighbor help", meta: "This is support, not employer-managed labor." },
                    { label: "Default move", value: "Pause if unsure", meta: "Escalate unclear or unsafe situations early." },
                ], preview: _jsx(PreviewFrame, { chromeLabel: "Safety checks", eyebrow: "Default guardrails", title: "Start with the non-negotiables.", body: "Every project should protect people, equipment, and the limits of community knowledge.", children: _jsx(ActionRail, { compact: true, items: [
                            { eyebrow: "PPE", title: "Use protective equipment and safe access.", body: "Ladders, anchors, and electrical isolation are not optional." },
                            { eyebrow: "Scope", title: "Stay inside your real level of training.", body: "Do not stretch community help into professional electrical work." },
                            { eyebrow: "Escalation", title: "Stop when the risk picture changes.", body: "Pause work and escalate when a job becomes unclear or unsafe." },
                        ] }) }) }) }), _jsx(PageReveal, { mode: "in-view", children: _jsxs("div", { className: "grid gap-4 lg:grid-cols-2", children: [_jsx(SurfacePanel, { as: "article", variant: "guide", layout: "preview", children: _jsxs("div", { className: "space-y-3", children: [_jsx("h2", { className: "text-lg font-semibold text-slate-900 dark:text-white", children: "Do" }), _jsxs("ul", { className: "list-inside list-disc space-y-2 text-sm text-slate-700 dark:text-slate-200", children: [_jsx("li", { children: "Use licensed electricians for any grid-tied or high-voltage work." }), _jsx("li", { children: "Wear PPE, de-energize circuits, and follow lock-out/tag-out where relevant." }), _jsx("li", { children: "Document shade surveys, torque checks, and maintenance schedules." }), _jsx("li", { children: "Match equipment to manufacturer specs; check voltage/current limits." }), _jsx("li", { children: "Ensure safe ladders, harnesses, and rooftop practices." })] })] }) }), _jsx(SurfacePanel, { as: "article", variant: "guide", layout: "preview", children: _jsxs("div", { className: "space-y-3", children: [_jsx("h2", { className: "text-lg font-semibold text-slate-900 dark:text-white", children: "Do not" }), _jsxs("ul", { className: "list-inside list-disc space-y-2 text-sm text-slate-700 dark:text-slate-200", children: [_jsx("li", { children: "Perform electrical work you're not qualified for." }), _jsx("li", { children: "Bypass safety devices or ignore manufacturer warnings." }), _jsx("li", { children: "Work at height without proper anchors or supervision." }), _jsx("li", { children: "Share unvetted advice as professional guidance." })] })] }) })] }) }), _jsx(PageReveal, { mode: "in-view", children: _jsx(SurfacePanel, { as: "article", variant: "guide", layout: "closeout", children: _jsxs("div", { className: "space-y-3", children: [_jsx("h2", { className: "text-lg font-semibold text-slate-900 dark:text-white", children: "Reporting & escalation" }), _jsx("p", { className: "text-sm text-slate-700 dark:text-slate-200", children: "If you see unsafe behavior or misrepresentation, let the organiser know and pause work until risks are resolved." })] }) }) })] }));
export default Safety;
