import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { Suspense } from "react";
import { Route, Routes, useLocation } from "react-router-dom";
import { AnimatePresence } from "framer-motion";
import Home from "@/pages/Home";
import Services from "@/pages/Services";
import Connect from "@/pages/Connect";
import ConnectHub from "@/pages/ConnectHub";
import LearnIndex from "@/routes/learn/index";
import LearnGuidePage from "@/routes/learn/[slug]";
import SolarNavigatorPage from "@/routes/solar-navigator";
import SolarNavigator from "@/pages/SolarNavigator";
import PlanHub from "@/pages/PlanHub";
import Projects from "@/pages/Projects";
import ProjectDetail from "@/pages/ProjectDetail";
import RequestHelp from "@/pages/RequestHelp";
import SignIn from "@/pages/SignIn";
import Register from "@/pages/Register";
import MyAccount from "@/pages/MyAccount";
import Dashboard from "@/pages/Dashboard";
import ProfilePage from "@/pages/ProfilePage";
import AccountCreate from "@/pages/AccountCreate";
import Safety from "@/pages/Safety";
import CommunityGuidelines from "@/pages/CommunityGuidelines";
import SolarSpinner from "@/components/ui/SolarSpinner";
import PageTransition from "@/app/PageTransition";
const SolarConfigurator = React.lazy(() => import("@/pages/SolarConfigurator"));
const AppRoutes = () => {
    const location = useLocation();
    return (_jsx(AnimatePresence, { mode: "wait", children: _jsxs(Routes, { location: location, children: [_jsx(Route, { path: "/", element: _jsx(PageTransition, { children: _jsx(Home, {}) }) }), _jsx(Route, { path: "/services", element: _jsx(PageTransition, { children: _jsx(Services, {}) }) }), _jsx(Route, { path: "/connect", element: _jsx(PageTransition, { children: _jsx(ConnectHub, {}) }) }), _jsx(Route, { path: "/connect/helpers", element: _jsx(PageTransition, { children: _jsx(Connect, {}) }) }), _jsx(Route, { path: "/learn", element: _jsx(PageTransition, { children: _jsx(LearnIndex, {}) }) }), _jsx(Route, { path: "/learn/:slug", element: _jsx(PageTransition, { children: _jsx(LearnGuidePage, {}) }) }), _jsx(Route, { path: "/plan", element: _jsx(PageTransition, { children: _jsx(PlanHub, {}) }) }), _jsx(Route, { path: "/solar-navigator", element: _jsx(PageTransition, { children: _jsx(SolarNavigatorPage, {}) }) }), _jsx(Route, { path: "/plan/navigator", element: _jsx(PageTransition, { children: _jsx(SolarNavigator, {}) }) }), _jsx(Route, { path: "/configurator", element: _jsx(PageTransition, { children: _jsx(Suspense, { fallback: _jsx("div", { className: "flex min-h-[600px] items-center justify-center", children: _jsx(SolarSpinner, { message: "Loading 3D Builder...", size: "lg" }) }), children: _jsx(SolarConfigurator, {}) }) }) }), _jsx(Route, { path: "/projects", element: _jsx(PageTransition, { children: _jsx(Projects, {}) }) }), _jsx(Route, { path: "/projects/:id", element: _jsx(PageTransition, { children: _jsx(ProjectDetail, {}) }) }), _jsx(Route, { path: "/request", element: _jsx(PageTransition, { children: _jsx(RequestHelp, {}) }) }), _jsx(Route, { path: "/request-help", element: _jsx(PageTransition, { children: _jsx(RequestHelp, {}) }) }), _jsx(Route, { path: "/sign-in", element: _jsx(PageTransition, { children: _jsx(SignIn, {}) }) }), _jsx(Route, { path: "/register", element: _jsx(PageTransition, { children: _jsx(Register, {}) }) }), _jsx(Route, { path: "/my-account", element: _jsx(PageTransition, { children: _jsx(MyAccount, {}) }) }), _jsx(Route, { path: "/dashboard", element: _jsx(PageTransition, { children: _jsx(Dashboard, {}) }) }), _jsx(Route, { path: "/profile/:id", element: _jsx(PageTransition, { children: _jsx(ProfilePage, {}) }) }), _jsx(Route, { path: "/account/create", element: _jsx(PageTransition, { children: _jsx(AccountCreate, {}) }) }), _jsx(Route, { path: "/safety", element: _jsx(PageTransition, { children: _jsx(Safety, {}) }) }), _jsx(Route, { path: "/community-guidelines", element: _jsx(PageTransition, { children: _jsx(CommunityGuidelines, {}) }) })] }, location.pathname) }));
};
export default AppRoutes;
